version: '3.9'

services:
  postgres:
    # image: postgis/postgis
    image: postgres:16-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ~/dev/postgres/wuv-web:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=wuv-web
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: jha@wuv.edu
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ~/dev/pgadmin/wuv-web:/var/lib/pgadmin
